name: kraken_video_player
description: Kraken Video Player
version: 0.4.2
homepage: https://openkraken.com

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.2.0"

dependencies:
  flutter:
    sdk: flutter
  meta: "^1.3.0"
  kraken: ^0.8.0

# The following section is specific to Futter.
flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.krakenvideoplayer
        pluginClass: KrakenVideoPlayerPlugin
      ios:
        pluginClass: FLTKrakenVideoPlayerPlugin
      macos:
        pluginClass: FLTKrakenVideoPlayerPlugin
