name: kraken_video_player
description: Kraken Video Player
version: 0.2.2
homepage: https://openkraken.com

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.12.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  video_player_platform_interface: ^1.0.1
  meta: "^1.0.5"
  kraken: ^0.6.6+2

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Futter.
flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.videoplayer
        pluginClass: VideoPlayerPlugin
      ios:
        pluginClass: FLTVideoPlayerPlugin
      macos:
        pluginClass: FLTVideoPlayerPlugin
